version: '3'
services:
  strapi:
    image: node:20-alpine
    command: >
      sh -c "
        apk add --no-cache git &&
        if [ ! -d /data/.git ]; then
          git clone https://your-git-repo-url.git /data
        else
          cd /data &&
          git fetch --all &&
          git reset --hard origin/your-branch-name
        fi &&
        npm install &&
        npm run develop
      "
    labels:
      '0': 'Backend Client For Handling Data'
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./strapi-project:/data
    working_dir: /data
    ports:
      - '1337:1337'
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
